CREATE TABLE IF NOT EXISTS pilot_pulse_responses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  role VARCHAR(50) NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  q1 SMALLINT NOT NULL,
  q2 SMALLINT NOT NULL,
  q3 SMALLINT NOT NULL,
  q4 SMALLINT NOT NULL,
  q5 SMALLINT NOT NULL,
  q6 SMALLINT NOT NULL,
  q7 SMALLINT NOT NULL,
  q8 SMALLINT NOT NULL,
  q9 SMALLINT NOT NULL,
  q10 SMALLINT NOT NULL,
  q11 SMALLINT NOT NULL,
  q12 SMALLINT NOT NULL,
  structural_score_s1 NUMERIC(4,2),
  structural_score_s2 NUMERIC(4,2),
  structural_score_s3 NUMERIC(4,2),
  structural_score_s4 NUMERIC(4,2),
  clarity_score_s1 SMALLINT,
  clarity_score_s2 SMALLINT,
  clarity_score_s3 SMALLINT,
  clarity_score_s4 SMALLINT,
  free_text TEXT
);
